---
env:
  browser: true
  es6: true
extends: airbnb-typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - "@typescript-eslint"
rules:
  react-hooks/rules-of-hooks": "error"
  react-hooks/exhaustive-deps": "warn"
